def on_pin_pressed_p0():
    pass
input.on_pin_pressed(TouchPin.P0, on_pin_pressed_p0)

def on_pin_pressed_p1():
    music.set_tempo(113)
    music.set_volume(255)
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.play_tone(277, music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.play_tone(349, music.beat(BeatFraction.HALF))
    music.rest(music.beat(BeatFraction.SIXTEENTH))
    music.play_tone(349, music.beat(BeatFraction.HALF))
    music.play_tone(311, music.beat(BeatFraction.DOUBLE))
    music.play_tone(208, music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.play_tone(208, music.beat(BeatFraction.QUARTER))
    music.play_tone(311, music.beat(BeatFraction.WHOLE))
    music.rest(music.beat(BeatFraction.SIXTEENTH))
    music.play_tone(311, music.beat(BeatFraction.WHOLE))
    music.play_tone(277, music.beat(BeatFraction.WHOLE))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.HALF))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.play_tone(262, music.beat(BeatFraction.QUARTER))
    music.play_tone(277, music.beat(BeatFraction.QUARTER))
    music.play_tone(233, music.beat(BeatFraction.QUARTER))
    music.play_tone(277, music.beat(BeatFraction.WHOLE))
    music.play_tone(311, music.beat(BeatFraction.HALF))
    music.play_tone(262, music.beat(BeatFraction.HALF))
    music.play_tone(233, music.beat(BeatFraction.HALF))
    music.play_tone(208, music.beat(BeatFraction.WHOLE))
    music.play_tone(175, music.beat(BeatFraction.HALF))
    music.play_tone(311, music.beat(BeatFraction.HALF))
    music.play_tone(277, music.beat(BeatFraction.WHOLE))
input.on_pin_pressed(TouchPin.P1, on_pin_pressed_p1)
